wit-ai/duckling_old

resources/default-config.clj
resources/duckling/corpus/et.communication.clj
resources/duckling/corpus/et.finance.clj
resources/duckling/corpus/et.measure.clj
resources/duckling/corpus/et.metrics.clj
resources/duckling/corpus/et.numbers.clj
resources/duckling/corpus/et.temperature.clj
resources/duckling/corpus/et.time.clj
resources/duckling/rules/et.communication.clj
resources/duckling/rules/et.cycles.clj
resources/duckling/rules/et.duration.clj
resources/duckling/rules/et.finance.clj
resources/duckling/rules/et.measure.clj
resources/duckling/rules/et.metrics.clj
resources/duckling/rules/et.numbers.clj
resources/duckling/rules/et.temperature.clj
resources/duckling/rules/et.time.clj

Actually using only numbers.* for now.

Initial support for Estonian language

---

resources/duckling/corpus/en.time.clj
resources/duckling/rules/en.time.clj
src/duckling/corpus.clj
src/duckling/time/api.clj

[in-prog] duckling for bookface

---

resources/duckling/corpus/fr.time.clj
resources/duckling/rules/fr.time.clj

cf http://villemin.gerard.free.fr/aHumanit/Langue/En_huit.htm

"<day-of-week> prochain" (fr) fix

---

resources/languages/en/corpus/time.clj
resources/languages/en/rules/time.clj

for things like
'from 2pm till 5pm thursday.' etc.

English: colloquialisms of 'until' for duration

---

resources/languages/pt/corpus/time.clj
resources/languages/pt/rules/time.clj

Decided to leave #97 unchanged to keep it consistent with other languages

Portuguese: #98, #101, Holidays

---

resources/languages/ar/rules/numbers.clj
resources/languages/de/rules/numbers.clj
resources/languages/de/rules/time.clj
resources/languages/en/rules/numbers.clj
resources/languages/en/rules/time.clj
resources/languages/es/rules/numbers.clj
resources/languages/es/rules/time.clj
resources/languages/et/rules/_time.clj
resources/languages/et/rules/numbers.clj
resources/languages/fr/rules/numbers.clj
resources/languages/fr/rules/time.clj
resources/languages/it/rules/numbers.clj
resources/languages/it/rules/time.clj
resources/languages/ja/rules/numbers.clj
resources/languages/pt/rules/numbers.clj
resources/languages/pt/rules/time.clj
resources/languages/ru/rules/numbers.clj
resources/languages/zh/rules/numbers.clj
resources/languages/zh/rules/time.clj
src/duckling/core.clj
src/duckling/engine.clj
src/duckling/time/obj.clj
src/duckling/time/prod.clj

Hi,
If you add `:global-vars {*warn-on-reflection* true}` to your project.clj and run `lein check` you would see a number of reflection warnings, performance hints and other depreciation messages. 
This PR fixes the performance issues and prevents reflection in a few hotspots. 
Cheers

fix reflection 

---

resources/languages/ar/rules/numbers.clj
resources/languages/de/rules/numbers.clj
resources/languages/de/rules/time.clj
resources/languages/en/rules/numbers.clj
resources/languages/en/rules/time.clj
resources/languages/es/rules/numbers.clj
resources/languages/es/rules/time.clj
resources/languages/et/rules/_time.clj
resources/languages/et/rules/numbers.clj
resources/languages/fr/rules/numbers.clj
resources/languages/fr/rules/time.clj
resources/languages/it/rules/numbers.clj
resources/languages/it/rules/time.clj
resources/languages/ja/rules/numbers.clj
resources/languages/pt/rules/numbers.clj
resources/languages/pt/rules/time.clj
resources/languages/ru/rules/numbers.clj
resources/languages/zh/rules/numbers.clj
resources/languages/zh/rules/time.clj
src/duckling/core.clj
src/duckling/engine.clj
src/duckling/time/obj.clj
src/duckling/time/prod.clj

Reverts wit-ai/duckling#120
@mpenet it looks like `(load!)` has some issues (lots of "not found"). Could you please look into it?

Revert "fix reflection "

---

resources/languages/ar/rules/numbers.clj
resources/languages/de/rules/numbers.clj
resources/languages/de/rules/time.clj
resources/languages/en/rules/numbers.clj
resources/languages/en/rules/time.clj
resources/languages/es/rules/numbers.clj
resources/languages/es/rules/time.clj
resources/languages/et/rules/_time.clj
resources/languages/et/rules/numbers.clj
resources/languages/fr/rules/numbers.clj
resources/languages/fr/rules/time.clj
resources/languages/it/rules/numbers.clj
resources/languages/it/rules/time.clj
resources/languages/ja/rules/numbers.clj
resources/languages/pt/rules/numbers.clj
resources/languages/pt/rules/time.clj
resources/languages/ru/rules/numbers.clj
resources/languages/zh/rules/numbers.clj
resources/languages/zh/rules/time.clj
src/duckling/core.clj
src/duckling/corpus.clj
src/duckling/engine.clj
src/duckling/ml/naivebayes.clj
src/duckling/time/obj.clj
src/duckling/time/prod.clj

Same as #120, without the error. 
I had missed an argument here https://github.com/wit-ai/duckling/pull/120/commits/9b9e2bcb3b20edf4cff4f892d02ce8bc466e33cd#diff-445fda74bfe70c94824eb8280a5c510fL71 (missing `(int minute)`). 
Cheers

kill reflection/performance warnings

---

resources/languages/da/corpus/numbers.clj
resources/languages/da/corpus/time.clj
resources/languages/da/rules/cycles.clj
resources/languages/da/rules/duration.clj
resources/languages/da/rules/numbers.clj
resources/languages/da/rules/time.clj

Adds support for parsing of Danish time, duration, numbers and cycles.

Support for Danish time, duration, numbers and cycles

---

resources/languages/es/rules/cycles.clj

Para que se pueda detectar:
- El ultimo sabado
- Los ultimos 3 meses
- Los últimos 2 dias
- La ultima semana
- Los ultimos 30 minutos
- Las ultimas 2 horas
- Las últimas 4 semanas
- El siguiente lunes

Spanish: Synonyms for better matches

---

resources/languages/es/rules/time.clj

EJ: Segundo lunes de septiembre

Spanish: nth <time> of <time>

---

resources/languages/fr/corpus/time.clj
resources/languages/fr/rules/cycles.clj
resources/languages/fr/rules/duration.clj
resources/languages/fr/rules/time.clj

toussaint, fête du travail, la veille, du 1er au 10 juillet, 1er week-end de septembre, etc.

[fr] time improvements

---

resources/languages/pl/corpus/pl.time.clj
resources/languages/pl/rules/pl.cycles.clj
resources/languages/pl/rules/pl.duration.clj
resources/languages/pl/rules/pl.numbers.clj
resources/languages/pl/rules/pl.time.clj

Implemented polish time,cycles,durations and numbers. The time corpus covers most of what the english one does.
Todo:
-general cleanup, remove some relics from english
-make sure all possible declensions are covered for each term
-more numbers
I'd appreciate any feedback.

Polish date/time

---

README.md

typo cn$core ==> zh$core

---

resources/languages/fr/corpus/time.clj
resources/languages/fr/rules/cycles.clj
resources/languages/fr/rules/time.clj

- "vendredi 5 à 15 heures" != "vendredi de 5 à 15 heures"
- au début de la semaine
- première/deuxième quinzaine de (mois)
- mais/plutôt/par exemple (lundi mais à 15 heures)

FR time improvements

---

circle.yml
project.clj
resources/languages/vi/corpus/finance.clj
resources/languages/vi/corpus/numbers.clj
resources/languages/vi/rules/finance.clj
resources/languages/vi/rules/numbers.clj

Add new Language Vietnamese. Complete number and finance

add vietnam language.( Number, Finance)

---

resources/languages/fr/corpus/time.clj
resources/languages/fr/rules/time.clj

Add french equivalent for "after/before/during" lunchtime using own french specific expressions (my work is inspired from the English version)
Also add "after work" french equivalent.
Those additions are tested in the test suite

Add fr lunch time and work time

---

resources/languages/nb/corpus/finance.clj
resources/languages/nb/corpus/numbers.clj
resources/languages/nb/corpus/time.clj
resources/languages/nb/rules/cycles.clj
resources/languages/nb/rules/duration.clj
resources/languages/nb/rules/finance.clj
resources/languages/nb/rules/numbers.clj
resources/languages/nb/rules/time.clj

Adds support for parsing of Norwegian (bokmål) time, duration, finance, numbers and cycles.

Norwegian language

---

resources/languages/sv/corpus/finance.clj
resources/languages/sv/corpus/numbers.clj
resources/languages/sv/corpus/time.clj
resources/languages/sv/rules/cycles.clj
resources/languages/sv/rules/duration.clj
resources/languages/sv/rules/finance.clj
resources/languages/sv/rules/numbers.clj
resources/languages/sv/rules/time.clj

Looking forward to seeing this deployed over at Wit.ai in the near future.
Thank you,
Magnus

Add Swedish language

---

resources/languages/en/rules/finance.clj

Added saudi,qatar,kuwaiti currency

Added saudi,qatar,kuwaiti currency

---

resources/languages/sv/corpus/finance.clj
resources/languages/sv/corpus/numbers.clj
resources/languages/sv/corpus/time.clj
resources/languages/sv/rules/cycles.clj
resources/languages/sv/rules/duration.clj
resources/languages/sv/rules/finance.clj
resources/languages/sv/rules/numbers.clj
resources/languages/sv/rules/time.clj

I finally managed to fix the rules to work with the corpus and avoid all errors. As a total beginner who never worked with Clojure before I'm pretty proud of myself hahah. Hope to see a merge soon so I can use it in production, thanks a ton!

Added Swedish language

---

project.clj
resources/languages/nl/corpus/numbers.clj
resources/languages/nl/rules/numbers.clj

Hi there,
I've added (with some help of @MichielDeMey) support for Dutch numbers. Still some errors on a couple of formats, but maybe you guys would like to help 😅 
Cheers!
Robin

Added Dutch language

---

resources/languages/it/corpus/time.clj
resources/languages/it/rules/cycles.clj
resources/languages/it/rules/duration.clj
resources/languages/it/rules/time.clj

I fixed many other problems found during our tests

More italian fixes

---

resources/languages/nl/corpus/measure.clj
resources/languages/nl/rules/measure.clj

Hi, I have translated the measure language to the dutch language.

translate measure to NL

---

src/duckling/resource.clj

Reuse JAR URL when listing resources

---

resources/languages/hr/corpus/communication.clj
resources/languages/hr/corpus/finance.clj
resources/languages/hr/corpus/measure.clj
resources/languages/hr/corpus/numbers.clj
resources/languages/hr/corpus/temperature.clj
resources/languages/hr/corpus/time.clj
resources/languages/hr/rules/communication.clj
resources/languages/hr/rules/cycles.clj
resources/languages/hr/rules/duration.clj
resources/languages/hr/rules/finance.clj
resources/languages/hr/rules/measure.clj
resources/languages/hr/rules/numbers.clj
resources/languages/hr/rules/temperature.clj
resources/languages/hr/rules/time.clj

Added Croatian(HR) language support for all elements

Croatian(HR) language support

---

resources/languages/pt/corpus/time.clj
resources/languages/pt/rules/time.clj

Example:
(EN) Show me the calendar **of this** month.
(PT) Me mostre o calendário **deste** mês.

[PT] Adds contractions of preposition 'desse' and 'deste' (of this) as current moment

---

resources/languages/pt/corpus/time.clj
resources/languages/pt/rules/time.clj

Reverts wit-ai/duckling_old#218

Revert "[PT] Adds contractions of preposition 'desse' and 'deste' (of this) as current moment"
