resources/duckling/corpus/en.time.clj
resources/duckling/rules/en.time.clj

With this change, duckling also parses "first Thursday in January". 
Even in the code, there is:
```clojure
"labor day" ;first Monday in September
```
Which wouldn't be parsed by duckling.

Added 'in' to work with cycles and nth

---

resources/duckling/corpus/en.finance.clj
resources/duckling/corpus/en.time.clj
resources/duckling/rules/en.finance.clj
resources/duckling/rules/en.time.clj

Add INR support
Support "in" in "Second tuesday in October"
In en.tim, make next only take non-latent times so it won't parse "next <integer>" as the year described by integer

Merge in recent PRs

---

project.clj
src/duckling/time/pred.clj

Patches issue #41. Outcome for "Friday April 24th from 8pm to 2am" was incorrect because "Friday April 24th" (or any <day of week> <day of month> intersection more than 100 weeks before or after the context reference time) was not resolving to a value.

Extend safe-max for compose in time.pred to allow for more distant intersections

---

project.clj
resources/duckling/rules/en.cycles.clj
src/duckling/core.clj
test/duckling/core_test.clj

This prevents having `learn/route-prob` being called many times for each sample

compute candidate prob only once

---

project.clj
src/duckling/time/prod.clj

This is semantically false, and also causes exceptions (e.g. when feeding those numbers to a `DateTime` constructor.)

fix bug causing floating-point number tokens to be treated as integers

---

resources/languages/en/corpus/time.clj
resources/languages/en/rules/cycles.clj
resources/languages/en/rules/time.clj
resources/languages/fr/corpus/time.clj
resources/languages/fr/rules/cycles.clj
resources/languages/fr/rules/time.clj

EN:
- IN september (in <named-month>)
- the following week (the following <cycle>)
FR:
- "L'après-midi" (the afternoon) should NOT be latent
- lundi EN soirée (monday evening)
- la semaine QUI SUIT (the following week)
- EN septembre (in september)
- LA dernière semaine d'août (the last week of August)
- lundi dans l'après-midi (monday in the afternoon)
- fix : samedi 12 à 18h (is not 'samedi de 12h à 18h')
- fix: 'avant 16h' should be a one-sided interval

various fixes in FR and EN :

---

resources/languages/de/rules/time.clj

abbreviation for October in German is okt (not oct)

fixed typo

---

resources/languages/de/rules/numbers.clj

There were missing production rules for "0"; the optional "r" in "keiner?" is already matched by the first alternative

Fix bug in named integer (0..19)

---

resources/languages/id/corpus/finance.clj
resources/languages/id/corpus/numbers.clj
resources/languages/id/rules/finance.clj
resources/languages/id/rules/numbers.clj

Add Indonesian numeric system and currency. Specifically, there are difference usage of comma and dot between Indonesian and English one (comma for decimal and dot for thousand separator). Is this okay?
Todo :
- more numbers
- generalize ordinal number

Extend new language : Indonesian but need more fix

---

resources/languages/fr/corpus/time.clj
resources/languages/fr/rules/time.clj

One case that wasn't handled in Duckling was "I prefer during the week" (I have multiple discussions where the user says that). I added the "en semaine" equivalent in the french version with a grain week.

Add en semaine for french version (during the week)

---

resources/languages/en/corpus/time.clj
resources/languages/en/rules/cycles.clj
resources/languages/en/rules/duration.clj

Added support for duration and cycle hours to support "hrs" format. Previously it required you to type out "hours" instead of "hrs"
"in 24hrs"
"in 24 hrs"
"last twenty four hrs"
"last 24 hrs"
"last 24hrs"

add support for "in 24hrs" for cycles and durations

---

src/duckling/engine.clj

Fix two issues with caught exceptions in production
1. `.printStackTrace` does **not** return the stack trace but prints it to
`stderr`
2. generally it is annoying in production if logs are cluttered with
java/clojure stack traces; rather, as was probably indented, pass the
stack trace and related information upwards in the exception

Do not print to stderr

---

resources/languages/en/corpus/time.clj
resources/languages/en/rules/duration.clj
resources/languages/fr/corpus/time.clj
resources/languages/fr/rules/duration.clj

Add 3 durations
* dans `une demi heure` (in half an hour)
* dans `un quart d'heure` (a quarter of an hour)
* dans `trois quarts d'heure` (Three-quarters of an hour)
Those expressions are very common in french. I looked at how it was done for `in half an hour` for the english version then copy/pasted it and translate it to french. I also added two other expressions that relied upon the same technique.
This should fix the issue #175

[FR] Add in half an hour

---

resources/languages/pl/corpus/numbers.clj
resources/languages/pl/rules/numbers.clj

For the beginning only numbers, the time should be next (work in progress).
Probably it is not fully optimized/polished but works well:
```clojure
duckling.core=> (load! {:languages ["pl"]})
{:pl$core (:number :ordinal)}
duckling.core=> (run)
:pl$core: 55 examples, 0 failed.
#'duckling.core/c
```
Regards from Poland!

pl numbers

---

resources/languages/en/corpus/time.clj
resources/languages/en/rules/cycles.clj
src/duckling/time/api.clj

Also added 'the' rule for <ordinal> quarter, which allows to parse something like
'2nd week of the 2nd qtr'
Which now correctly yields
```
{
"start": 0,
"dim": "time",
"end": 23,
"body": "2nd week of the 2nd qtr",
"value": {
"values": [],
"grain": "week",
"type": "value",
"value": "2016-04-11T00:00:00.000Z"
}
}
```

Added slang words for year and quarter

---

resources/languages/fr/corpus/time.clj
resources/languages/fr/rules/time.clj

I've added some improvements to the french rules :
- `Milieu de journée` (literal translation would be midday but it does not mean 12am but more like during the middle of the day)
- `Milieu d'après-midi` (midafternoon)
- `Milieu de matinée` (midmorning)
- Add `à l'heure du déjeuner` to be equal to `pendant le déjeuner` (during lunch). Just another way to say it
- Add `fin du mois` (end of month)
Those changes are real cases sentences/expressions from what people use to say in french.
Don't hesitate to tell me if you would like a modification to those changes or if something seems off.

Add french end of month and mid(morning|day|afternoon)

---

resources/languages/it/corpus/time.clj
resources/languages/it/rules/cycles.clj
resources/languages/it/rules/duration.clj
resources/languages/it/rules/numbers.clj
resources/languages/it/rules/time.clj

I'm here with my pull request as I announced in the Facebook thread ;-)
Italian now supports intervals, holidays, precision, seasons; clock is set to 24 hours and allows using “di pomeriggio”; many fixes.

Fix and extend italian support for time and durations

---

resources/languages/es/corpus/communication.clj
resources/languages/es/rules/communication.clj

Hi, this pull request modifies Spanish email regex to detect mails with hyphens and underscores as well as in English.
If anything is wrong please tell me and I will fix it as soon as possible to get this merged. I tried to follow all the steps from
Thanks!

Add support for emails with hyphens and underscores in ES

---

resources/languages/de/rules/time.clj

Fixed this by adding some minimal requirement on the context, i.e. that there
is a space after the "H" or "A" or that this appears at the end of the
text.
Actually the rule for "am|pm" is pretty useless for German, at least "am|pm" is at
most a corner case.

Expressions like "ein Hotel" or "ein Angebot" in German are not 1h

---

resources/languages/tr/corpus/numbers.clj
resources/languages/tr/rules/numbers.clj

This adds support for Turkish language to duckling -at least for numbers. As I have a need to use the wit.ai for my studies, I saw that Turkish language support was very limited. So, I decided to contribute and add support for Turkish, at least in numbers - which will be very very useful for my studies.
I used the English version of the rules file to create Turkish version. I have a **_very_** **_very_** limited experience with Clojure also it is my first contribution on GitHub. Thus, any advice and feedback are appreciated :)
Thanks.

Turkish support (numbers only)

---

src/duckling/engine.clj

The warning message was formatted, and then this string was used as a format for warnf.  This fails for certain sentences.
```
DuplicateFormatFlagsException Flags = '-'  java.util.Formatter$Flags.parse (Formatter.java:4186)
```

Fix DuplicateFormatFlagsException when max-iter-reached exceeded

---

resources/languages/sv/rules/time.clj

Fixed the rules a bit by adding `vid` (to allow for `imorgon vid 12` => `tomorrow by 12`).

Updated Swedish time rules

---

resources/languages/en/corpus/time.clj
resources/languages/en/rules/time.clj
src/duckling/time/prod.clj

This commit adds two new rules to "better" handle ambiguous time intervals
suffixed with an AM or PM. Typically, "from 7 to 8 PM" and "between 7 and 8 PM"
refer to the interval from 1900 to 2000, and _not_ the interval 0700 to 2000.
This behavior has been a bit annoying to end users of our application. I recognize this
change represents an opinionated design decision, but I do think my proposed semantics
are more mainstream.

[EN] More natural disambiguation of intervals
